# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    needs: [build_and_test]
    if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/master') }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker
      run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    - name: Build and push to Docker Hub
      run: |
        docker build --target production --tag $DOCKER_USERNAME/strava_app:latest .
        docker push $DOCKER_USERNAME/strava_app:latest
    # - name: Release app on Azure
    #   run: curl -dH -X POST $AZURE_DEPLOY_WEBHOOK

