# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  deploy:
    name: Deploy application
    runs-on: ubuntu-latest
    if: ${{ (github.event_name == 'push') && (github.ref == 'refs/heads/master') }}
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}'
    - name: Docker Auth
      id: docker-auth
      uses: 'docker/login-action@v1'
      with:
        registry: 'gcr.io'
        username: _json_key
        password: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
    - name: Build and push to Google artifact registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev
        docker build --target production --tag us-central1-docker.pkg.dev/stravaapp-361611/strava-app/strava_app:latest .
        docker push us-central1-docker.pkg.dev/stravaapp-361611/strava-app/strava_app:latest
    - name: 'Deploy to cloud run'
      uses: 'google-github-actions/deploy-cloudrun@v0'
      with:
        service: 'strava-app'
        image: 'us-central1-docker.pkg.dev/stravaapp-361611/strava-app/strava_app:latest'

    # - name: Login to Docker
    #   run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
    # - name: Build and push to Docker Hub
    #   run: |
    #     docker build --target production --tag $DOCKER_USERNAME/strava_app:latest .
    #     docker push $DOCKER_USERNAME/strava_app:latest
    

    # - name: Release app on Azure
    #   run: curl -dH -X POST $AZURE_DEPLOY_WEBHOOK

